import ReceiptLongRoundedIcon from '@mui/icons-material/ReceiptLongRounded';
import { useEffect, useMemo, useState } from 'react'; import { useTheme } from '@mui/material/styles';
import CrudEntityPage from '../../organization/shared/CrudEntityPage'; import { useAuth } from '../../../app/AuthContext'; import { organizationService } from '../../../services/organizationService'; import { employeeService } from '../../../services/employee_hr_management/employee/employeeService'; import { payrollService } from '../../../services/employee_hr_management/payroll/payrollService';
import { getOwnCompanyPrefill, opt, req, rowsFrom, toDecimal, toInt } from '../shared/hrCrudCommon';
export default function PayrollPage(){ const theme=useTheme(); const {token,auth}=useAuth(); const [companies,setCompanies]=useState([]); const [employees,setEmployees]=useState([]); const [payrollStatuses,setPayrollStatuses]=useState([]); const [payMethods,setPayMethods]=useState([]);
useEffect(()=>{(async()=>{ if(!token)return; try{ const [cr,er,ps,pm]=await Promise.all([organizationService.listCompanies(token,{activeOnly:true}),employeeService.listEmployees(token,{sortBy:'firstName',sortDir:'asc'}),organizationService.enumValues('payroll_status',{activeOnly:true}),organizationService.enumValues('payroll_payment_method',{activeOnly:true})]); setCompanies(rowsFrom(cr).map(c=>({id:c.companyId,code:c.companyCode,name:c.companyName}))); setEmployees(rowsFrom(er).map(e=>({id:e.employeeId,companyId:e.companyId,code:e.employeeCode,name:`${e.firstName||''} ${e.lastName||''}`.trim()||e.employeeCode}))); setPayrollStatuses(rowsFrom(ps)); setPayMethods(rowsFrom(pm)); }catch{ setCompanies([]);setEmployees([]);setPayrollStatuses([]);setPayMethods([]);} })(); },[token]);
const own=useMemo(()=>getOwnCompanyPrefill(auth,companies),[auth,companies]); const companyById=useMemo(()=>Object.fromEntries(companies.map(c=>[String(c.id),c])),[companies]); const empById=useMemo(()=>Object.fromEntries(employees.map(e=>[String(e.id),`${e.name}${e.code?` (${e.code})`:''}`])),[employees]); const statusById=useMemo(()=>Object.fromEntries(payrollStatuses.map(s=>[String(s.id),s.name])),[payrollStatuses]); const methodById=useMemo(()=>Object.fromEntries(payMethods.map(m=>[String(m.id),m.name])),[payMethods]);
const empOptsByCompany=useMemo(()=>{const m={}; employees.forEach(e=>{const k=String(e.companyId||''); (m[k]??=[]).push({value:String(e.id),label:`${e.name}${e.code?` (${e.code})`:''}`});}); return m;},[employees]); const companyOpts=useMemo(()=>[{value:'',label:'All Companies'},...companies.map(c=>({value:String(c.id),label:`${c.name} (${c.code})`}))],[companies]); const companyFormOpts=useMemo(()=>[{value:'',label:'Select Company'},...companies.map(c=>({value:String(c.id),label:`${c.name} (${c.code})`}))],[companies]); const statusOpts=useMemo(()=>[{value:'',label:'All Statuses'},...payrollStatuses.map(s=>({value:String(s.id),label:s.name}))],[payrollStatuses]); const statusFormOpts=useMemo(()=>[{value:'',label:'Select Status'},...payrollStatuses.map(s=>({value:String(s.id),label:s.name}))],[payrollStatuses]); const methodFormOpts=useMemo(()=>[{value:'',label:'Select Payment Method'},...payMethods.map(s=>({value:String(s.id),label:s.name}))],[payMethods]);
return <CrudEntityPage title="Payroll" icon={<ReceiptLongRoundedIcon sx={{color:'#fff',fontSize:20}}/>} gradient={`linear-gradient(135deg, ${theme.palette.primary.main}, ${theme.palette.secondary.main})`} idKey="payrollId" prefillForm={own} prefillFilters={own?{companyId:own.companyId}:null}
columns={[{key:'companyId',label:'Company',render:r=>companyById[String(r.companyId)]?.name||r.companyCode||'-'},{key:'employeeId',label:'Employee',render:r=>empById[String(r.employeeId)]||'-'},{key:'payrollMonth',label:'Month'},{key:'payrollYear',label:'Year'},{key:'netSalary',label:'Net Salary'},{key:'paymentMethodId',label:'Payment Method',render:r=>methodById[String(r.paymentMethodId)]||'-'},{key:'statusId',label:'Status',render:r=>statusById[String(r.statusId)]||'-'}]}
filterFields={[{key:'companyId',label:'Company',type:'autocomplete',options:companyOpts},{key:'employeeId',label:'Employee',type:'autocomplete',optionsByForm:f=>[{value:'',label:'All Employees'},...(empOptsByCompany[String(f?.companyId||'')]||[])]},{key:'payrollMonth',label:'Month'},{key:'payrollYear',label:'Year'},{key:'statusId',label:'Status',type:'autocomplete',options:statusOpts}]}
formFields={[{key:'companyId',label:'Company',type:'autocomplete',options:companyFormOpts,readonlyOnEdit:true},{key:'companyCode',label:'Company Code',readOnly:true},{key:'employeeId',label:'Employee',type:'autocomplete',optionsByForm:f=>[{value:'',label:'Select Employee'},...(empOptsByCompany[String(f?.companyId||'')]||[])]},{key:'payrollMonth',label:'Payroll Month',type:'number'},{key:'payrollYear',label:'Payroll Year',type:'number'},{key:'basicSalary',label:'Basic Salary',type:'number'},{key:'overtimeHours',label:'Overtime Hours',type:'number'},{key:'overtimeAmount',label:'Overtime Amount',type:'number'},{key:'rationTotal',label:'Ration Total',type:'number'},{key:'allowancesTotal',label:'Allowances Total',type:'number'},{key:'advanceDeductions',label:'Advance Deductions',type:'number'},{key:'otherDeductions',label:'Other Deductions',type:'number'},{key:'netSalary',label:'Net Salary',type:'number'},{key:'paymentDate',label:'Payment Date',type:'date'},{key:'paymentMethodId',label:'Payment Method',type:'autocomplete',options:methodFormOpts},{key:'statusId',label:'Status',type:'autocomplete',options:statusFormOpts}]}
defaultFilters={{companyId:'',employeeId:'',payrollMonth:'',payrollYear:'',statusId:'',sortBy:'payrollYear',sortDir:'desc'}} emptyForm={{companyId:'',companyCode:'',employeeId:'',payrollMonth:'',payrollYear:'',basicSalary:'',overtimeHours:'',overtimeAmount:'',rationTotal:'',allowancesTotal:'',advanceDeductions:'',otherDeductions:'',netSalary:'',paymentDate:'',paymentMethodId:'',statusId:''}}
normalizePayload={f=>({companyId:opt(f.companyId),companyCode:req(f.companyCode),employeeId:opt(f.employeeId),payrollMonth:toInt(f.payrollMonth),payrollYear:toInt(f.payrollYear),basicSalary:toDecimal(f.basicSalary),overtimeHours:toDecimal(f.overtimeHours),overtimeAmount:toDecimal(f.overtimeAmount),rationTotal:toDecimal(f.rationTotal),allowancesTotal:toDecimal(f.allowancesTotal),advanceDeductions:toDecimal(f.advanceDeductions),otherDeductions:toDecimal(f.otherDeductions),netSalary:toDecimal(f.netSalary),paymentDate:opt(f.paymentDate),paymentMethodId:toInt(f.paymentMethodId),statusId:toInt(f.statusId)})}
onFormFieldChange={(n,k,v)=>k==='companyId'?{...n,companyCode:companyById[String(v)]?.code||'',employeeId:''}:n}
listFetcher={payrollService.list} getByIdFetcher={payrollService.getById} createFetcher={payrollService.create} updateFetcher={payrollService.update} deleteFetcher={payrollService.delete} autoSearch autoSearchDebounceMs={350} fitViewport viewportOffset={190}/>; }
