import RestaurantMenuRoundedIcon from '@mui/icons-material/RestaurantMenuRounded';
import { useEffect, useMemo, useState } from 'react'; import { useTheme } from '@mui/material/styles';
import CrudEntityPage from '../../organization/shared/CrudEntityPage'; import { useAuth } from '../../../app/AuthContext'; import { organizationService } from '../../../services/organizationService'; import { rationPolicyService } from '../../../services/employee_hr_management/ration_policy/rationPolicyService';
import { getOwnCompanyPrefill, opt, req, rowsFrom, toBool, toDecimal } from '../shared/hrCrudCommon';
export default function RationPolicyPage(){ const theme=useTheme(); const {token,auth}=useAuth(); const [companies,setCompanies]=useState([]);
useEffect(()=>{(async()=>{ if(!token) return; try{ const raw=await organizationService.listCompanies(token,{activeOnly:true}); setCompanies(rowsFrom(raw).map(c=>({id:c.companyId,code:c.companyCode,name:c.companyName}))); }catch{ setCompanies([]);} })(); },[token]);
const ownCompanyPrefill=useMemo(()=>getOwnCompanyPrefill(auth,companies),[auth,companies]); const companyById=useMemo(()=>Object.fromEntries(companies.map(c=>[String(c.id),c])),[companies]); const companyOpts=useMemo(()=>[{value:'',label:'All Companies'},...companies.map(c=>({value:String(c.id),label:`${c.name} (${c.code})`}))],[companies]); const companyFormOpts=useMemo(()=>[{value:'',label:'Select Company'},...companies.map(c=>({value:String(c.id),label:`${c.name} (${c.code})`}))],[companies]);
return <CrudEntityPage title="Ration Policies" icon={<RestaurantMenuRoundedIcon sx={{color:'#fff',fontSize:20}}/>} gradient={`linear-gradient(135deg, ${theme.palette.primary.main}, ${theme.palette.secondary.main})`} idKey="rationPolicyId" prefillForm={ownCompanyPrefill} prefillFilters={ownCompanyPrefill?{companyId:ownCompanyPrefill.companyId}:null}
columns={[{key:'companyId',label:'Company',render:r=>companyById[String(r.companyId)]?.name||r.companyCode||'-'},{key:'policyName',label:'Policy Name'},{key:'perDayAmount',label:'Per Day Amount'},{key:'isActive',label:'Active',type:'boolean'},{key:'notes',label:'Notes'}]}
filterFields={[{key:'companyId',label:'Company',type:'autocomplete',options:companyOpts},{key:'policyName_like',label:'Policy Name'},{key:'isActive',label:'Active',type:'boolean'}]}
formFields={[{key:'companyId',label:'Company',type:'autocomplete',options:companyFormOpts,readonlyOnEdit:true},{key:'companyCode',label:'Company Code',readOnly:true},{key:'policyName',label:'Policy Name'},{key:'perDayAmount',label:'Per Day Amount',type:'number'},{key:'isActive',label:'Is Active',type:'boolean'},{key:'notes',label:'Notes',fullWidth:true,minWidth:320}]}
defaultFilters={{companyId:'',policyName_like:'',isActive:'',sortBy:'policyName',sortDir:'asc'}} emptyForm={{companyId:'',companyCode:'',policyName:'',perDayAmount:'',isActive:'true',notes:''}}
normalizePayload={f=>({companyId:opt(f.companyId),companyCode:req(f.companyCode),policyName:req(f.policyName),perDayAmount:toDecimal(f.perDayAmount),isActive:toBool(f.isActive),notes:opt(f.notes)})}
onFormFieldChange={(n,k,v)=>k==='companyId'?{...n,companyCode:companyById[String(v)]?.code||''}:n}
listFetcher={rationPolicyService.list} getByIdFetcher={rationPolicyService.getById} createFetcher={rationPolicyService.create} updateFetcher={rationPolicyService.update} deleteFetcher={rationPolicyService.delete} autoSearch autoSearchDebounceMs={350} fitViewport viewportOffset={190}/>; }
