import PriceCheckRoundedIcon from '@mui/icons-material/PriceCheckRounded';
import { useEffect, useMemo, useState } from 'react'; import { useTheme } from '@mui/material/styles';
import CrudEntityPage from '../../organization/shared/CrudEntityPage'; import { useAuth } from '../../../app/AuthContext'; import { organizationService } from '../../../services/organizationService'; import { payrollService } from '../../../services/employee_hr_management/payroll/payrollService'; import { payrollDeductionService } from '../../../services/employee_hr_management/payroll_deduction/payrollDeductionService'; import { employeeService } from '../../../services/employee_hr_management/employee/employeeService';
import { getOwnCompanyPrefill, opt, req, rowsFrom, toDecimal, toInt } from '../shared/hrCrudCommon';
export default function PayrollDeductionPage(){ const theme=useTheme(); const {token,auth}=useAuth(); const [companies,setCompanies]=useState([]); const [payrolls,setPayrolls]=useState([]); const [employees,setEmployees]=useState([]); const [dedTypes,setDedTypes]=useState([]);
useEffect(()=>{(async()=>{ if(!token)return; try{ const [cr,pr,er,dt]=await Promise.all([organizationService.listCompanies(token,{activeOnly:true}),payrollService.list(token,{sortBy:'payrollYear',sortDir:'desc'}),employeeService.listEmployees(token,{sortBy:'firstName',sortDir:'asc'}),organizationService.enumValues('payroll_deduction_type',{activeOnly:true})]); setCompanies(rowsFrom(cr).map(c=>({id:c.companyId,code:c.companyCode,name:c.companyName}))); setPayrolls(rowsFrom(pr)); setEmployees(rowsFrom(er).map(e=>({id:e.employeeId,companyId:e.companyId,code:e.employeeCode,name:`${e.firstName||''} ${e.lastName||''}`.trim()||e.employeeCode}))); setDedTypes(rowsFrom(dt)); }catch{ setCompanies([]);setPayrolls([]);setEmployees([]);setDedTypes([]);} })(); },[token]);
const own=useMemo(()=>getOwnCompanyPrefill(auth,companies),[auth,companies]); const companyById=useMemo(()=>Object.fromEntries(companies.map(c=>[String(c.id),c])),[companies]); const empById=useMemo(()=>Object.fromEntries(employees.map(e=>[String(e.id),`${e.name}${e.code?` (${e.code})`:''}`])),[employees]); const dedTypeById=useMemo(()=>Object.fromEntries(dedTypes.map(d=>[String(d.id),d.name])),[dedTypes]);
const payrollOptsByCompany=useMemo(()=>{const m={}; payrolls.forEach(p=>{const k=String(p.companyId||''); const label=`${p.payrollMonth||'?'}/${p.payrollYear||'?'} - ${empById[String(p.employeeId)]||String(p.employeeId||'')}`; (m[k]??=[]).push({value:String(p.payrollId),label});}); return m;},[payrolls,empById]);
const companyOpts=useMemo(()=>[{value:'',label:'All Companies'},...companies.map(c=>({value:String(c.id),label:`${c.name} (${c.code})`}))],[companies]); const companyFormOpts=useMemo(()=>[{value:'',label:'Select Company'},...companies.map(c=>({value:String(c.id),label:`${c.name} (${c.code})`}))],[companies]); const dedTypeOpts=useMemo(()=>[{value:'',label:'All Types'},...dedTypes.map(d=>({value:String(d.id),label:d.name}))],[dedTypes]); const dedTypeFormOpts=useMemo(()=>[{value:'',label:'Select Type'},...dedTypes.map(d=>({value:String(d.id),label:d.name}))],[dedTypes]);
return <CrudEntityPage title="Payroll Deductions" icon={<PriceCheckRoundedIcon sx={{color:'#fff',fontSize:20}}/>} gradient={`linear-gradient(135deg, ${theme.palette.primary.main}, ${theme.palette.secondary.main})`} idKey="payDedId" prefillForm={own} prefillFilters={own?{companyId:own.companyId}:null}
columns={[{key:'companyId',label:'Company',render:r=>companyById[String(r.companyId)]?.name||r.companyCode||'-'},{key:'payrollId',label:'Payroll',render:r=>{const p=payrolls.find(x=>String(x.payrollId)===String(r.payrollId)); return p?`${p.payrollMonth}/${p.payrollYear} - ${empById[String(p.employeeId)]||''}`:'-';}},{key:'deductionTypeId',label:'Deduction Type',render:r=>dedTypeById[String(r.deductionTypeId)]||'-'},{key:'amount',label:'Amount'},{key:'note',label:'Note'}]}
filterFields={[{key:'companyId',label:'Company',type:'autocomplete',options:companyOpts},{key:'payrollId',label:'Payroll',type:'autocomplete',optionsByForm:f=>[{value:'',label:'All Payrolls'},...(payrollOptsByCompany[String(f?.companyId||'')]||[])]},{key:'deductionTypeId',label:'Deduction Type',type:'autocomplete',options:dedTypeOpts}]}
formFields={[{key:'companyId',label:'Company',type:'autocomplete',options:companyFormOpts,readonlyOnEdit:true},{key:'companyCode',label:'Company Code',readOnly:true},{key:'payrollId',label:'Payroll',type:'autocomplete',optionsByForm:f=>[{value:'',label:'Select Payroll'},...(payrollOptsByCompany[String(f?.companyId||'')]||[])]},{key:'deductionTypeId',label:'Deduction Type',type:'autocomplete',options:dedTypeFormOpts},{key:'referenceId',label:'Reference Id (UUID)'},{key:'amount',label:'Amount',type:'number'},{key:'note',label:'Note',fullWidth:true,minWidth:320}]}
defaultFilters={{companyId:'',payrollId:'',deductionTypeId:'',sortBy:'payDedId',sortDir:'desc'}} emptyForm={{companyId:'',companyCode:'',payrollId:'',deductionTypeId:'',referenceId:'',amount:'',note:''}}
normalizePayload={f=>({companyId:opt(f.companyId),companyCode:req(f.companyCode),payrollId:opt(f.payrollId),deductionTypeId:toInt(f.deductionTypeId),referenceId:opt(f.referenceId),amount:toDecimal(f.amount),note:opt(f.note)})}
onFormFieldChange={(n,k,v)=>k==='companyId'?{...n,companyCode:companyById[String(v)]?.code||'',payrollId:''}:n}
listFetcher={payrollDeductionService.list} getByIdFetcher={payrollDeductionService.getById} createFetcher={payrollDeductionService.create} updateFetcher={payrollDeductionService.update} deleteFetcher={payrollDeductionService.delete} autoSearch autoSearchDebounceMs={350} fitViewport viewportOffset={190}/>; }
