import FastfoodRoundedIcon from '@mui/icons-material/FastfoodRounded';
import { useEffect, useMemo, useState } from 'react'; import { useTheme } from '@mui/material/styles';
import CrudEntityPage from '../../organization/shared/CrudEntityPage'; import { useAuth } from '../../../app/AuthContext'; import { organizationService } from '../../../services/organizationService'; import { employeeService } from '../../../services/employee_hr_management/employee/employeeService'; import { rationDistributionService } from '../../../services/employee_hr_management/ration_distribution/rationDistributionService';
import { getOwnCompanyPrefill, opt, req, rowsFrom, toDecimal, toInt } from '../shared/hrCrudCommon';
export default function RationDistributionPage(){ const theme=useTheme(); const {token,auth}=useAuth(); const [companies,setCompanies]=useState([]); const [employees,setEmployees]=useState([]); const [projects,setProjects]=useState([]);
useEffect(()=>{(async()=>{ if(!token)return; try{ const [cr,er,pr]=await Promise.all([organizationService.listCompanies(token,{activeOnly:true}),employeeService.listEmployees(token,{sortBy:'firstName',sortDir:'asc'}),organizationService.listProjects(token,{activeOnly:true})]); setCompanies(rowsFrom(cr).map(c=>({id:c.companyId,code:c.companyCode,name:c.companyName}))); setEmployees(rowsFrom(er).map(e=>({id:e.employeeId,companyId:e.companyId,code:e.employeeCode,name:`${e.firstName||''} ${e.lastName||''}`.trim()||e.employeeCode}))); setProjects(rowsFrom(pr).map(p=>({id:p.projectId,companyId:p.companyId,code:p.projectCode,name:p.projectName}))); }catch{ setCompanies([]);setEmployees([]);setProjects([]);} })(); },[token]);
const own=useMemo(()=>getOwnCompanyPrefill(auth,companies),[auth,companies]); const companyById=useMemo(()=>Object.fromEntries(companies.map(c=>[String(c.id),c])),[companies]); const empById=useMemo(()=>Object.fromEntries(employees.map(e=>[String(e.id),`${e.name}${e.code?` (${e.code})`:''}`])),[employees]); const projById=useMemo(()=>Object.fromEntries(projects.map(p=>[String(p.id),`${p.name}${p.code?` (${p.code})`:''}`])),[projects]);
const empOptsByCompany=useMemo(()=>{const m={}; employees.forEach(e=>{const k=String(e.companyId||''); (m[k]??=[]).push({value:String(e.id),label:`${e.name}${e.code?` (${e.code})`:''}`});}); return m;},[employees]); const projOptsByCompany=useMemo(()=>{const m={}; projects.forEach(p=>{const k=String(p.companyId||''); (m[k]??=[]).push({value:String(p.id),label:`${p.name}${p.code?` (${p.code})`:''}`});}); return m;},[projects]);
const companyOpts=useMemo(()=>[{value:'',label:'All Companies'},...companies.map(c=>({value:String(c.id),label:`${c.name} (${c.code})`}))],[companies]); const companyFormOpts=useMemo(()=>[{value:'',label:'Select Company'},...companies.map(c=>({value:String(c.id),label:`${c.name} (${c.code})`}))],[companies]);
return <CrudEntityPage title="Ration Distributions" icon={<FastfoodRoundedIcon sx={{color:'#fff',fontSize:20}}/>} gradient={`linear-gradient(135deg, ${theme.palette.primary.main}, ${theme.palette.secondary.main})`} idKey="rationId" prefillForm={own} prefillFilters={own?{companyId:own.companyId}:null}
columns={[{key:'companyId',label:'Company',render:r=>companyById[String(r.companyId)]?.name||r.companyCode||'-'},{key:'employeeId',label:'Employee',render:r=>empById[String(r.employeeId)]||'-'},{key:'projectId',label:'Project',render:r=>projById[String(r.projectId)]||'-'},{key:'rationDate',label:'Ration Date'},{key:'mealsCount',label:'Meals'},{key:'amount',label:'Amount'}]}
filterFields={[{key:'companyId',label:'Company',type:'autocomplete',options:companyOpts},{key:'employeeId',label:'Employee',type:'autocomplete',optionsByForm:f=>[{value:'',label:'All Employees'},...(empOptsByCompany[String(f?.companyId||'')]||[])]},{key:'rationDate_from',label:'Date From',type:'date'},{key:'rationDate_to',label:'Date To',type:'date'}]}
formFields={[{key:'companyId',label:'Company',type:'autocomplete',options:companyFormOpts,readonlyOnEdit:true},{key:'companyCode',label:'Company Code',readOnly:true},{key:'employeeId',label:'Employee',type:'autocomplete',optionsByForm:f=>[{value:'',label:'Select Employee'},...(empOptsByCompany[String(f?.companyId||'')]||[])]},{key:'projectId',label:'Project',type:'autocomplete',optionsByForm:f=>[{value:'',label:'Optional Project'},...(projOptsByCompany[String(f?.companyId||'')]||[])]},{key:'rationDate',label:'Ration Date',type:'date'},{key:'mealsCount',label:'Meals Count',type:'number'},{key:'amount',label:'Amount',type:'number'},{key:'notes',label:'Notes',fullWidth:true,minWidth:320}]}
defaultFilters={{companyId:'',employeeId:'',rationDate_from:'',rationDate_to:'',sortBy:'rationDate',sortDir:'desc'}} emptyForm={{companyId:'',companyCode:'',employeeId:'',projectId:'',rationDate:'',mealsCount:'1',amount:'',notes:''}}
normalizePayload={f=>({companyId:opt(f.companyId),companyCode:req(f.companyCode),employeeId:opt(f.employeeId),projectId:opt(f.projectId),rationDate:opt(f.rationDate),mealsCount:toInt(f.mealsCount),amount:toDecimal(f.amount),notes:opt(f.notes)})}
onFormFieldChange={(n,k,v)=>k==='companyId'?{...n,companyCode:companyById[String(v)]?.code||'',employeeId:'',projectId:''}:n}
listFetcher={rationDistributionService.list} getByIdFetcher={rationDistributionService.getById} createFetcher={rationDistributionService.create} updateFetcher={rationDistributionService.update} deleteFetcher={rationDistributionService.delete} autoSearch autoSearchDebounceMs={350} fitViewport viewportOffset={190}/>; }
