import PaymentsRoundedIcon from '@mui/icons-material/PaymentsRounded';
import { useEffect, useMemo, useState } from 'react'; import { useTheme } from '@mui/material/styles';
import CrudEntityPage from '../../organization/shared/CrudEntityPage'; import { useAuth } from '../../../app/AuthContext'; import { organizationService } from '../../../services/organizationService'; import { employeeService } from '../../../services/employee_hr_management/employee/employeeService'; import { employeeAdvanceService } from '../../../services/employee_hr_management/employee_advance/employeeAdvanceService';
import { getOwnCompanyPrefill, opt, req, rowsFrom, toDecimal, toInt } from '../shared/hrCrudCommon';
export default function EmployeeAdvancePage(){ const theme=useTheme(); const {token,auth}=useAuth(); const [companies,setCompanies]=useState([]); const [employees,setEmployees]=useState([]); const [advanceStatuses,setAdvanceStatuses]=useState([]);
useEffect(()=>{(async()=>{ if(!token)return; try{ const [cr,er,asr]=await Promise.all([organizationService.listCompanies(token,{activeOnly:true}),employeeService.listEmployees(token,{sortBy:'firstName',sortDir:'asc'}),organizationService.enumValues('advance_status',{activeOnly:true})]); setCompanies(rowsFrom(cr).map(c=>({id:c.companyId,code:c.companyCode,name:c.companyName}))); setEmployees(rowsFrom(er).map(e=>({id:e.employeeId,companyId:e.companyId,code:e.employeeCode,name:`${e.firstName||''} ${e.lastName||''}`.trim()||e.employeeCode}))); setAdvanceStatuses(rowsFrom(asr)); }catch{ setCompanies([]);setEmployees([]);setAdvanceStatuses([]);} })(); },[token]);
const own=useMemo(()=>getOwnCompanyPrefill(auth,companies),[auth,companies]); const companyById=useMemo(()=>Object.fromEntries(companies.map(c=>[String(c.id),c])),[companies]); const empById=useMemo(()=>Object.fromEntries(employees.map(e=>[String(e.id),`${e.name}${e.code?` (${e.code})`:''}`])),[employees]); const statusById=useMemo(()=>Object.fromEntries(advanceStatuses.map(s=>[String(s.id),s.name])),[advanceStatuses]);
const empOptsByCompany=useMemo(()=>{const m={}; employees.forEach(e=>{const k=String(e.companyId||''); (m[k]??=[]).push({value:String(e.id),label:`${e.name}${e.code?` (${e.code})`:''}`});}); return m;},[employees]); const companyOpts=useMemo(()=>[{value:'',label:'All Companies'},...companies.map(c=>({value:String(c.id),label:`${c.name} (${c.code})`}))],[companies]); const companyFormOpts=useMemo(()=>[{value:'',label:'Select Company'},...companies.map(c=>({value:String(c.id),label:`${c.name} (${c.code})`}))],[companies]); const statusOpts=useMemo(()=>[{value:'',label:'All Statuses'},...advanceStatuses.map(s=>({value:String(s.id),label:s.name}))],[advanceStatuses]); const statusFormOpts=useMemo(()=>[{value:'',label:'Select Status'},...advanceStatuses.map(s=>({value:String(s.id),label:s.name}))],[advanceStatuses]);
return <CrudEntityPage title="Employee Advances" icon={<PaymentsRoundedIcon sx={{color:'#fff',fontSize:20}}/>} gradient={`linear-gradient(135deg, ${theme.palette.primary.main}, ${theme.palette.secondary.main})`} idKey="advanceId" prefillForm={own} prefillFilters={own?{companyId:own.companyId}:null}
columns={[{key:'companyId',label:'Company',render:r=>companyById[String(r.companyId)]?.name||r.companyCode||'-'},{key:'employeeId',label:'Employee',render:r=>empById[String(r.employeeId)]||'-'},{key:'issuedDate',label:'Issued Date'},{key:'amount',label:'Amount'},{key:'balance',label:'Balance'},{key:'statusId',label:'Status',render:r=>statusById[String(r.statusId)]||'-'}]}
filterFields={[{key:'companyId',label:'Company',type:'autocomplete',options:companyOpts},{key:'employeeId',label:'Employee',type:'autocomplete',optionsByForm:f=>[{value:'',label:'All Employees'},...(empOptsByCompany[String(f?.companyId||'')]||[])]},{key:'issuedDate_from',label:'Issued From',type:'date'},{key:'issuedDate_to',label:'Issued To',type:'date'},{key:'statusId',label:'Status',type:'autocomplete',options:statusOpts}]}
formFields={[{key:'companyId',label:'Company',type:'autocomplete',options:companyFormOpts,readonlyOnEdit:true},{key:'companyCode',label:'Company Code',readOnly:true},{key:'employeeId',label:'Employee',type:'autocomplete',optionsByForm:f=>[{value:'',label:'Select Employee'},...(empOptsByCompany[String(f?.companyId||'')]||[])]},{key:'issuedDate',label:'Issued Date',type:'date'},{key:'amount',label:'Amount',type:'number'},{key:'balance',label:'Balance',type:'number'},{key:'statusId',label:'Status',type:'autocomplete',options:statusFormOpts},{key:'purpose',label:'Purpose',fullWidth:true,minWidth:320}]}
defaultFilters={{companyId:'',employeeId:'',issuedDate_from:'',issuedDate_to:'',statusId:'',sortBy:'issuedDate',sortDir:'desc'}} emptyForm={{companyId:'',companyCode:'',employeeId:'',issuedDate:'',amount:'',balance:'',statusId:'',purpose:''}}
normalizePayload={f=>({companyId:opt(f.companyId),companyCode:req(f.companyCode),employeeId:opt(f.employeeId),issuedDate:opt(f.issuedDate),amount:toDecimal(f.amount),balance:toDecimal(f.balance),statusId:toInt(f.statusId),purpose:opt(f.purpose)})}
onFormFieldChange={(n,k,v)=>k==='companyId'?{...n,companyCode:companyById[String(v)]?.code||'',employeeId:''}:n}
listFetcher={employeeAdvanceService.list} getByIdFetcher={employeeAdvanceService.getById} createFetcher={employeeAdvanceService.create} updateFetcher={employeeAdvanceService.update} deleteFetcher={employeeAdvanceService.delete} autoSearch autoSearchDebounceMs={350} fitViewport viewportOffset={190}/>; }
